# Use the official MySQL image as the base image
# FROM mysql:latest

# Set the authentication plugin to caching_sha2_password
# RUN echo 'default_authentication_plugin = caching_sha2_password' >> /etc/mysql/my.cnf