version: "3.8"

services:
  postgres:
    container_name: postgreshealthassist
    image: postgres
    env_file:
      - ./.env
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${SQLDB_USER}
      POSTGRES_PASSWORD: ${SQLDB_PASSWORD}
      POSTGRES_DB: ${SQLDB_DATABASE}
    ports:
      - "5433:5432"
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
      - ./entrypoint:/docker-entrypoint-initdb.d
#  mysql:
#    container_name: mysql
#    image: mysql
#    env_file:
#      - ./.env
#    restart: unless-stopped
#    environment:
#      MYSQL_ROOT_PASSWORD: ${SQLDB_PASSWORD}
#      MYSQL_DATABASE: ${SQLDB_DATABASE}
#      MYSQL_SSL: "false"
#    ports:
#      - "3607:3606"
#    volumes:
#      - ./db/mysql:/var/lib/mysql
#      - ./config/:/etc/mysql/my.cnf
volumes:
  db: